<<<<<<< HEAD
﻿import { useState } from "react";
const C={navy:"#0A1628",navyMid:"#0F1F3D",navyCard:"#111E35",indigo:"#4F46E5",indigoL:"#6366F1",gold:"#F59E0B",teal:"#14B8A6",green:"#10B981",pink:"#EC4899",purple:"#8B5CF6",white:"#F0F4FF",muted:"#94A3B8",border:"rgba(99,102,241,0.18)",error:"#EF4444"};
const px=v=>`${v}px`;const card=(e={})=>({background:C.navyCard,border:`1px solid ${C.border}`,borderRadius:px(14),...e});
const FC=[{q:"What is the powerhouse of the cell?",a:"Mitochondria  produces ATP through cellular respiration.",subject:"Biology"},{q:"State Newton's Second Law of Motion",a:"F = ma. Force equals mass multiplied by acceleration.",subject:"Physics"},{q:"What is osmosis?",a:"Movement of water through a semi-permeable membrane from high to low water concentration.",subject:"Biology"},{q:"Define photosynthesis",a:"Green plants use sunlight, water and CO2 to produce glucose and oxygen.",subject:"Biology"},{q:"What is the quadratic formula?",a:"x = (-b  (b-4ac)) / 2a",subject:"Mathematics"}];
const DQ=[{text:"Symbol for Iron on the periodic table:",options:["Fe","Ir","In","Io"],correct:0,subject:"Chemistry"},{text:"Year Tanzania gained independence:",options:["1960","1961","1963","1964"],correct:1,subject:"History"},{text:"Photosynthesis produces which gas?",options:["CO2","N2","O2","H2"],correct:2,subject:"Biology"}];
const LB=[{rank:1,name:"Joseph Mwangi",school:"Alliance HS Nairobi",xp:8420,streak:45,badge:""},{rank:2,name:"Fatuma Ally",school:"Zanzibar HS",xp:7850,streak:38,badge:""},{rank:3,name:"Amina Hassan",school:"Mwl. Nyerere SS",xp:3450,streak:12,badge:"",isMe:true},{rank:4,name:"David Kimani",school:"Kilimanjaro SS",xp:3200,streak:9,badge:""},{rank:5,name:"Grace Nyambura",school:"Moshi Girls HS",xp:2980,streak:7,badge:""},{rank:6,name:"Hassan Omar",school:"Dodoma HS",xp:2750,streak:5,badge:""},{rank:7,name:"Neema Juma",school:"Dar es Salaam HS",xp:2600,streak:4,badge:""},{rank:8,name:"Peter Masanja",school:"Mbeya SS",xp:2400,streak:6,badge:""}];
const BADGES=[{icon:"",name:"Streak Master",desc:"12-day study streak",earned:true,color:C.gold},{icon:"",name:"Speed Solver",desc:"Complete exam in half time",earned:true,color:C.indigo},{icon:"",name:"Paper Champion",desc:"Complete 30+ papers",earned:true,color:C.teal},{icon:"",name:"Top Performer",desc:"Score 90%+ on 5 exams",earned:true,color:C.purple},{icon:"",name:"Accuracy Ace",desc:"95%+ accuracy in a subject",earned:true,color:C.green},{icon:"",name:"NECTA Ready",desc:"Score 80%+ on 10 NECTA papers",earned:false,color:C.gold},{icon:"",name:"Knowledge King",desc:"Master all topics in a subject",earned:false,color:C.pink},{icon:"",name:"Diamond Scholar",desc:"Reach Level 20",earned:false,color:C.indigoL},{icon:"",name:"Top 10 Nation",desc:"Reach national top 10",earned:false,color:C.teal},{icon:"",name:"Rocket Start",desc:"Complete 5 exams in first week",earned:false,color:C.error}];
const MISSIONS=[{icon:"",text:"Complete 1 past paper today",xp:50,progress:0,target:1},{icon:"",text:"Score above 70% in Biology",xp:100,progress:0,target:1},{icon:"",text:"Study for 30 minutes",xp:30,progress:20,target:30},{icon:"",text:"Extend streak to 13 days",xp:75,progress:12,target:13}];
const NAV=[{icon:"",label:"Dashboard"},{icon:"",label:"Past Papers"},{icon:"",label:"Analytics"},{icon:"",label:"Leaderboard"},{icon:"",label:"AI Tutor"},{icon:"",label:"Activities",active:true},{icon:"",label:"Settings"}];
const Sidebar=()=>(<div style={{width:px(200),minHeight:"100vh",background:C.navyMid,borderRight:`1px solid ${C.border}`,display:"flex",flexDirection:"column",padding:"20px 0",flexShrink:0}}><div style={{padding:"0 16px 20px",borderBottom:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",gap:px(8)}}><div style={{width:px(32),height:px(32),borderRadius:px(8),background:`linear-gradient(135deg,${C.indigo},${C.gold})`,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:px(14),color:"#fff"}}>E</div><div><div style={{fontWeight:800,fontSize:px(13),color:C.white}}>ExamHub</div><div style={{fontSize:px(10),color:C.gold}}>Tanzania</div></div></div></div><nav style={{padding:"12px 8px",flex:1}}>{NAV.map(n=>(<div key={n.label} style={{display:"flex",alignItems:"center",gap:px(8),padding:"9px 10px",borderRadius:px(8),marginBottom:px(2),background:n.active?`${C.indigo}22`:"transparent",border:n.active?`1px solid ${C.indigo}44`:"1px solid transparent",cursor:"pointer",color:n.active?C.indigoL:C.muted}}><span style={{fontSize:px(15)}}>{n.icon}</span><span style={{fontSize:px(12),fontWeight:n.active?700:400}}>{n.label}</span></div>))}</nav></div>);
const Flashcard=()=>{const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);const c=FC[idx];return(<div style={{...card({padding:"28px"}),textAlign:"center"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:px(20)}}><div style={{fontWeight:700,fontSize:px(16),color:C.white}}> Flashcards</div><span style={{fontSize:px(12),color:C.muted}}>{idx+1}/{FC.length}  {c.subject}</span></div><div onClick={()=>setFlipped(f=>!f)} style={{minHeight:px(160),background:flipped?C.green+"18":C.navyMid,border:`1px solid ${flipped?C.green:C.border}`,borderRadius:px(14),padding:"28px 24px",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",marginBottom:px(20),transition:"all 0.3s"}}><p style={{fontSize:px(16),color:C.white,lineHeight:1.7,margin:0,fontWeight:flipped?600:400}}>{flipped?c.a:c.q}</p></div><p style={{fontSize:px(12),color:C.muted,marginBottom:px(16)}}>{flipped?"Answer revealed":"Click card to reveal answer"}</p><div style={{display:"flex",gap:px(10),justifyContent:"center"}}><button onClick={()=>{setIdx(i=>Math.max(0,i-1));setFlipped(false);}} disabled={idx===0} style={{padding:"9px 18px",borderRadius:px(8),background:"transparent",border:`1px solid ${C.border}`,color:C.muted,fontSize:px(13),cursor:"pointer",opacity:idx===0?0.4:1}}> Prev</button><button onClick={()=>setFlipped(f=>!f)} style={{padding:"9px 24px",borderRadius:px(8),background:C.indigo,border:"none",color:"#fff",fontSize:px(13),fontWeight:600,cursor:"pointer"}}>Flip</button><button onClick={()=>{setIdx(i=>Math.min(FC.length-1,i+1));setFlipped(false);}} disabled={idx===FC.length-1} style={{padding:"9px 18px",borderRadius:px(8),background:"transparent",border:`1px solid ${C.border}`,color:C.muted,fontSize:px(13),cursor:"pointer",opacity:idx===FC.length-1?0.4:1}}>Next </button></div></div>);};
const DailyQuiz=()=>{const[qIdx,setQIdx]=useState(0);const[sel,setSel]=useState(null);const[score,setScore]=useState(0);const[done,setDone]=useState(false);if(done)return(<div style={{...card({padding:"28px"}),textAlign:"center"}}><div style={{fontSize:px(48),marginBottom:px(12)}}></div><div style={{fontWeight:800,fontSize:px(22),color:C.white,marginBottom:px(8)}}>Quiz Complete!</div><div style={{fontSize:px(16),color:C.gold,marginBottom:px(20)}}>Score: {score}/{DQ.length}  +{score*30} XP earned</div><button onClick={()=>{setQIdx(0);setSel(null);setScore(0);setDone(false);}} style={{padding:"11px 28px",borderRadius:px(10),background:C.indigo,border:"none",color:"#fff",fontWeight:600,cursor:"pointer"}}>Play Again</button></div>);
const q=DQ[qIdx];return(<div style={{...card({padding:"28px"})}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:px(20)}}><div style={{fontWeight:700,fontSize:px(16),color:C.white}}> Daily Quiz</div><div style={{fontSize:px(12),color:C.muted}}>Q{qIdx+1}/{DQ.length}  {q.subject}</div></div><div style={{height:px(4),background:C.border,borderRadius:px(2),marginBottom:px(20)}}><div style={{width:`${((qIdx+1)/DQ.length)*100}%`,height:"100%",background:`linear-gradient(90deg,${C.indigo},${C.gold})`,borderRadius:px(2)}}/></div><p style={{fontSize:px(16),color:C.white,lineHeight:1.6,fontWeight:500,marginBottom:px(20)}}>{q.text}</p><div style={{display:"flex",flexDirection:"column",gap:px(8),marginBottom:px(16)}}>{q.options.map((opt,i)=>{const isCo=i===q.correct;const isSel=i===sel;const show=sel!==null;return(<div key={i} onClick={()=>sel===null&&setSel(i)} style={{padding:"12px 16px",borderRadius:px(10),cursor:sel===null?"pointer":"default",border:`1px solid ${show?(isCo?C.green:isSel?C.error:C.border):(isSel?C.indigo:C.border)}`,background:show?(isCo?C.green+"20":isSel?C.error+"20":"transparent"):"transparent",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:px(14),color:C.white}}><strong style={{color:C.indigoL}}>{String.fromCharCode(65+i)}.</strong> {opt}</span>{show&&isCo&&<span style={{color:C.green}}></span>}{show&&isSel&&!isCo&&<span style={{color:C.error}}></span>}</div>);})}  </div>{sel!==null&&(<button onClick={()=>{if(sel===q.correct)setScore(s=>s+1);if(qIdx<DQ.length-1){setQIdx(i=>i+1);setSel(null);}else setDone(true);}} style={{width:"100%",padding:"11px 0",borderRadius:px(10),background:C.indigo,border:"none",color:"#fff",fontWeight:600,fontSize:px(14),cursor:"pointer"}}>{qIdx<DQ.length-1?"Next Question ":"Finish Quiz"}</button>)}</div>);};
const BadgeGrid=()=>(<div style={{...card({padding:"24px"})}}><div style={{fontWeight:700,fontSize:px(16),color:C.white,marginBottom:px(16)}}> All Badges</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(175px,1fr))",gap:px(10)}}>{BADGES.map((b,i)=>(<div key={i} style={{background:b.earned?b.color+"15":C.navyMid,border:`1px solid ${b.earned?b.color+"44":C.border}`,borderRadius:px(12),padding:"16px 14px",opacity:b.earned?1:0.55}}><div style={{fontSize:px(28),marginBottom:px(8)}}>{b.icon}</div><div style={{fontWeight:700,fontSize:px(13),color:b.earned?C.white:C.muted,marginBottom:px(4)}}>{b.name}</div><div style={{fontSize:px(11),color:C.muted,lineHeight:1.5}}>{b.desc}</div><div style={{marginTop:px(8),fontSize:px(11),color:b.earned?b.color:C.muted,fontWeight:600}}>{b.earned?" Earned":" Locked"}</div></div>))}</div></div>);
const Missions=()=>(<div style={{...card({padding:"24px"})}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:px(16)}}><div style={{fontWeight:700,fontSize:px(16),color:C.white}}> Daily Missions</div><span style={{fontSize:px(12),color:C.muted}}>Resets in 6h 42m</span></div><div style={{display:"flex",flexDirection:"column",gap:px(12)}}>{MISSIONS.map((m,i)=>(<div key={i} style={{padding:"14px 16px",borderRadius:px(10),background:C.navyMid,border:`1px solid ${C.border}`}}><div style={{display:"flex",alignItems:"center",gap:px(10),marginBottom:px(8)}}><span style={{fontSize:px(20)}}>{m.icon}</span><div style={{flex:1}}><div style={{fontWeight:600,fontSize:px(13),color:C.white}}>{m.text}</div></div><div style={{padding:"3px 10px",borderRadius:px(100),background:C.gold+"22",color:C.gold,fontSize:px(11),fontWeight:700}}>+{m.xp} XP</div></div><div style={{height:px(4),background:C.border,borderRadius:px(2)}}><div style={{width:`${Math.round((m.progress/m.target)*100)}%`,height:"100%",borderRadius:px(2),background:C.indigo}}/></div><div style={{fontSize:px(11),color:C.muted,marginTop:px(4)}}>{m.progress}/{m.target}</div></div>))}</div></div>);
const Leaderboard=()=>(<div style={{...card({padding:"24px"})}}><div style={{fontWeight:700,fontSize:px(16),color:C.white,marginBottom:px(16)}}> National Leaderboard</div><div style={{display:"flex",flexDirection:"column",gap:px(8)}}>{LB.map((p,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:px(12),padding:"12px 14px",borderRadius:px(10),background:p.isMe?C.indigo+"20":C.navyMid,border:`1px solid ${p.isMe?C.indigo+"44":C.border}`}}><div style={{width:px(28),height:px(28),borderRadius:"50%",background:p.rank<=3?C.gold+"22":C.border,display:"flex",alignItems:"center",justifyContent:"center",fontSize:px(13),fontWeight:800,color:p.rank<=3?C.gold:C.muted,flexShrink:0}}>{p.badge||p.rank}</div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:p.isMe?700:500,fontSize:px(13),color:p.isMe?C.indigoL:C.white,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p.name}{p.isMe?" (You)":""}</div><div style={{fontSize:px(11),color:C.muted,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p.school}</div></div><div style={{textAlign:"right",flexShrink:0}}><div style={{fontWeight:700,fontSize:px(14),color:C.gold}}>{p.xp.toLocaleString()} XP</div><div style={{fontSize:px(11),color:C.muted}}> {p.streak}d</div></div></div>))}</div></div>);
export default function Gamification(){return(<div style={{display:"flex",minHeight:"100vh",background:C.navy,color:C.white,fontFamily:"'Inter',system-ui,sans-serif"}}><Sidebar/><div style={{flex:1,minWidth:0}}><div style={{padding:"16px 24px",borderBottom:`1px solid ${C.border}`,background:C.navy,display:"flex",alignItems:"center",justifyContent:"space-between",position:"sticky",top:0,zIndex:10}}><div><div style={{fontWeight:800,fontSize:px(20)}}>Activities </div><div style={{fontSize:px(13),color:C.muted}}>Learn, earn XP, climb the leaderboard</div></div><div style={{display:"flex",gap:px(10)}}><div style={{padding:"8px 16px",borderRadius:px(10),background:C.gold+"18",border:`1px solid ${C.gold}33`,fontSize:px(13),fontWeight:700,color:C.gold}}> 3,450 XP</div><div style={{padding:"8px 16px",borderRadius:px(10),background:C.indigo+"18",border:`1px solid ${C.indigo}33`,fontSize:px(13),fontWeight:700,color:C.indigoL}}> 12 streak</div></div></div><main style={{padding:"24px",overflowY:"auto"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:px(16),marginBottom:px(20)}}><Flashcard/><DailyQuiz/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:px(16),marginBottom:px(20)}}><Missions/><Leaderboard/></div><BadgeGrid/></main></div></div>);}
=======
export default function Phase7() {
  const C = {
    navy:"#0A1628", navyMid:"#0F1F3D", navyCard:"#111E35",
    indigo:"#4F46E5", indigoL:"#6366F1", gold:"#F59E0B",
    white:"#F0F4FF", muted:"#94A3B8", border:"rgba(99,102,241,0.18)",
  };
  return (
    <div style={{display:"flex",minHeight:"100vh",background:C.navy,color:C.white,fontFamily:"'Inter',system-ui,sans-serif"}}>
      <div style={{width:220,minHeight:"100vh",background:C.navyMid,borderRight:"1px solid "+C.border,display:"flex",flexDirection:"column",padding:"24px 0",flexShrink:0}}>
        <div style={{padding:"0 20px 24px",borderBottom:"1px solid "+C.border,display:"flex",alignItems:"center",gap:10}}>
          <div style={{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,"+C.indigo+","+C.gold+")",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:16,color:"#fff"}}>E</div>
          <div>
            <div style={{fontWeight:800,fontSize:15,color:C.white}}>ExamHub</div>
            <div style={{fontSize:11,color:C.gold,fontWeight:600}}>Tanzania</div>
          </div>
        </div>
        <nav style={{padding:"12px 10px",flex:1}}>
          {[["Home","/"],["Dashboard","/dashboard"],["Past Papers","/papers"],["Analytics","/analytics"],["Activities","/activities"],["Admin","/admin"]].map(([label,path])=>(
            <a key={label} href={path} style={{display:"flex",alignItems:"center",padding:"10px 12px",borderRadius:10,marginBottom:2,color:C.muted,textDecoration:"none",fontSize:13,border:"1px solid transparent"}}>{label}</a>
          ))}
        </nav>
      </div>
      <div style={{flex:1,display:"flex",flexDirection:"column"}}>
        <div style={{padding:"16px 24px",borderBottom:"1px solid "+C.border,background:C.navy,position:"sticky",top:0,zIndex:10}}>
          <div style={{fontSize:20,fontWeight:800,color:C.white}}>Gamification and Activities</div>
          <div style={{fontSize:13,color:C.muted,marginTop:2}}>Phase 7 — Run ExamHub-Complete-Setup.ps1 to load full component</div>
        </div>
        <main style={{flex:1,padding:"40px 24px",display:"flex",alignItems:"center",justifyContent:"center"}}>
          <div style={{textAlign:"center",maxWidth:480}}>
            <div style={{fontSize:64,marginBottom:16}}>📋</div>
            <h2 style={{fontSize:22,fontWeight:800,color:C.white,marginBottom:10}}>Gamification and Activities</h2>
            <p style={{color:C.muted,fontSize:14,lineHeight:1.7,marginBottom:28}}>
              The full Phase 7 component is in <strong style={{color:C.indigoL}}>ExamHub-Complete-Setup.ps1</strong>. Run it on your Windows machine and the full UI will appear here.
            </p>
            <div style={{display:"flex",gap:12,justifyContent:"center"}}>
              <a href="/" style={{padding:"11px 22px",borderRadius:10,background:C.indigo,color:"#fff",fontWeight:600,fontSize:14,textDecoration:"none"}}>Home</a>
              <a href="/dashboard" style={{padding:"11px 22px",borderRadius:10,background:"transparent",border:"1px solid "+C.border,color:C.muted,fontWeight:600,fontSize:14,textDecoration:"none"}}>Dashboard</a>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
>>>>>>> 0b3c81e9470c74fd27c37a680978282ae4c33e18
