<<<<<<< HEAD
﻿import { useState, useEffect, useRef } from "react";
const C={navy:"#0A1628",navyMid:"#0F1F3D",navyCard:"#111E35",indigo:"#4F46E5",indigoL:"#6366F1",gold:"#F59E0B",teal:"#14B8A6",green:"#10B981",purple:"#8B5CF6",white:"#F0F4FF",muted:"#94A3B8",border:"rgba(99,102,241,0.18)",error:"#EF4444"};
const px=v=>`${v}px`;
const card=(e={})=>({background:C.navyCard,border:`1px solid ${C.border}`,borderRadius:px(14),...e});
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;
const QS=[{id:1,type:"mcq",marks:2,text:"Which organelle is responsible for ATP production in eukaryotic cells?",options:["Ribosome","Mitochondria","Golgi apparatus","Endoplasmic reticulum"],correct:1,topic:"Cell Biology"},{id:2,type:"mcq",marks:2,text:"Primary function of the lymphatic system?",options:["Blood filtration","Hormone secretion","Return excess tissue fluid to blood","Oxygen transport"],correct:2,topic:"Human Physiology"},{id:3,type:"truefalse",marks:1,text:"Osmosis is the movement of solute molecules from high to low concentration.",correct:false,topic:"Cell Transport"},{id:4,type:"mcq",marks:2,text:"During meiosis II, chromosomes in each cell:",options:["Double","Remain the same","Are halved","Quadruple"],correct:1,topic:"Cell Division"},{id:5,type:"short",marks:3,text:"Explain the role of enzymes in digestion. Name TWO enzymes, where produced and their substrate.",placeholder:"Write your answer here...",topic:"Digestion"},{id:6,type:"mcq",marks:2,text:"Which is NOT a function of the liver?",options:["Detoxification","Bile production","Insulin secretion","Glycogen storage"],correct:2,topic:"Human Physiology"},{id:7,type:"truefalse",marks:1,text:"Photosynthesis occurs in the mitochondria of plant cells.",correct:false,topic:"Photosynthesis"},{id:8,type:"mcq",marks:2,text:"The process by which organisms maintain a stable internal environment:",options:["Metabolism","Homeostasis","Respiration","Excretion"],correct:1,topic:"Homeostasis"},{id:9,type:"short",marks:4,text:"Describe natural selection with reference to Darwin's theory of evolution. Use an example.",placeholder:"Write your answer here...",topic:"Evolution"},{id:10,type:"mcq",marks:2,text:"HIV/AIDS destroys which white blood cells?",options:["Neutrophils","B-lymphocytes","T-helper cells (CD4+)","Eosinophils"],correct:2,topic:"Immunity"}];
const EXAM={subject:"Biology",level:"Form 4",year:2023,type:"NECTA",paper:"Paper 1",duration:180};
const MCQ=({q,ans,onAns})=>(<div style={{display:"flex",flexDirection:"column",gap:px(10)}}>{q.options.map((opt,i)=>{const sel=ans===i;return(<div key={i} onClick={()=>onAns(i)} style={{display:"flex",alignItems:"center",gap:px(12),padding:"14px 18px",borderRadius:px(12),cursor:"pointer",border:`1px solid ${sel?C.indigo:C.border}`,background:sel?`${C.indigo}20`:C.navyMid,transition:"all 0.15s"}}><div style={{width:px(28),height:px(28),borderRadius:"50%",border:`2px solid ${sel?C.indigo:C.border}`,background:sel?C.indigo:"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,fontSize:px(12),fontWeight:700,color:sel?"#fff":C.muted}}>{String.fromCharCode(65+i)}</div><span style={{fontSize:px(15),color:sel?C.white:C.muted,fontWeight:sel?600:400}}>{opt}</span></div>);})}</div>);
const TF=({q,ans,onAns})=>(<div style={{display:"flex",gap:px(12)}}>{[true,false].map(v=>(<div key={String(v)} onClick={()=>onAns(v)} style={{flex:1,padding:"18px 0",borderRadius:px(12),textAlign:"center",cursor:"pointer",border:`1px solid ${ans===v?(v?C.green:C.error):C.border}`,background:ans===v?(v?C.green+"20":C.error+"20"):C.navyMid,transition:"all 0.15s"}}><div style={{fontSize:px(28),marginBottom:px(6)}}>{v?"":""}</div><div style={{fontWeight:700,fontSize:px(15),color:ans===v?(v?C.green:C.error):C.muted}}>{v?"TRUE":"FALSE"}</div></div>))}</div>);
const SA=({q,ans,onAns})=>(<textarea value={ans||""} onChange={e=>onAns(e.target.value)} placeholder={q.placeholder} rows={6} style={{width:"100%",padding:"14px 16px",borderRadius:px(12),background:C.navyMid,border:`1px solid ${C.border}`,color:C.white,fontSize:px(14),lineHeight:1.7,resize:"vertical",outline:"none",boxSizing:"border-box"}} onFocus={e=>e.target.style.borderColor=C.indigo} onBlur={e=>e.target.style.borderColor=C.border}/>);
export default function ExamEngine(){const[phase,setPhase]=useState("start");const[cur,setCur]=useState(0);const[answers,setAnswers]=useState({});const[timeLeft,setTimeLeft]=useState(EXAM.duration*60);const[flagged,setFlagged]=useState(new Set());const timerRef=useRef(null);const totalQ=QS.length;const q=QS[cur];const answered=Object.keys(answers).length;const pct=Math.round((answered/totalQ)*100);const timeColor=timeLeft<300?C.error:timeLeft<600?C.gold:C.green;
useEffect(()=>{if(phase!=="exam")return;timerRef.current=setInterval(()=>{setTimeLeft(t=>{if(t<=1){clearInterval(timerRef.current);setPhase("done");return 0;}return t-1;});},1000);return()=>clearInterval(timerRef.current);},[phase]);
const setAns=(id,val)=>setAnswers(p=>({...p,[id]:val}));
const toggleFlag=id=>setFlagged(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});
if(phase==="start")return(<div style={{minHeight:"100vh",background:C.navy,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Inter',system-ui,sans-serif",padding:"24px"}}><div style={{...card({padding:"40px 36px",maxWidth:px(520),width:"100%"})}}><div style={{textAlign:"center",marginBottom:px(32)}}><div style={{fontSize:px(48),marginBottom:px(12)}}></div><h1 style={{fontSize:px(24),fontWeight:900,color:C.white,marginBottom:px(8)}}>{EXAM.subject}</h1><p style={{color:C.muted,fontSize:px(14)}}>{EXAM.year} {EXAM.type}  {EXAM.paper}  {EXAM.level}</p></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:px(10),marginBottom:px(28)}}>{[{icon:"",label:"Questions",value:totalQ},{icon:"",label:"Duration",value:`${EXAM.duration} min`},{icon:"",label:"Total Marks",value:QS.reduce((a,q)=>a+q.marks,0)},{icon:"",label:"Year",value:EXAM.year}].map(s=>(<div key={s.label} style={{background:C.navyMid,borderRadius:px(10),padding:"14px",border:`1px solid ${C.border}`,textAlign:"center"}}><div style={{fontSize:px(22),marginBottom:px(4)}}>{s.icon}</div><div style={{fontSize:px(18),fontWeight:800,color:C.white}}>{s.value}</div><div style={{fontSize:px(12),color:C.muted}}>{s.label}</div></div>))}</div><div style={{background:C.gold+"12",border:`1px solid ${C.gold}33`,borderRadius:px(10),padding:"14px 16px",marginBottom:px(24),fontSize:px(13),color:C.gold,lineHeight:1.6}}> Once you begin, the {EXAM.duration}-minute timer starts and cannot be paused. Answers are auto-saved.</div><div style={{display:"flex",flexDirection:"column",gap:px(8),fontSize:px(13),color:C.muted,marginBottom:px(28)}}>{["Read each question carefully","MCQs: select one option only","Short answers: write clearly and completely","You can flag questions to review later"].map((t,i)=>(<div key={i} style={{display:"flex",gap:px(8)}}><span style={{color:C.indigo,fontWeight:700}}></span><span>{t}</span></div>))}</div><button onClick={()=>setPhase("exam")} style={{width:"100%",padding:"14px 0",borderRadius:px(12),background:`linear-gradient(135deg,${C.indigo},${C.indigoL})`,border:"none",color:"#fff",fontWeight:700,fontSize:px(16),cursor:"pointer"}}>Begin Exam  {EXAM.duration} min </button></div></div>);
if(phase==="done")return(<div style={{minHeight:"100vh",background:C.navy,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Inter',system-ui,sans-serif",padding:"24px"}}><div style={{...card({padding:"40px 36px",maxWidth:px(500),width:"100%"}),textAlign:"center"}}><div style={{fontSize:px(64),marginBottom:px(16)}}></div><h1 style={{fontSize:px(26),fontWeight:900,color:C.white,marginBottom:px(8)}}>Exam Submitted!</h1><p style={{color:C.muted,fontSize:px(14),marginBottom:px(28)}}>Your answers are saved. View your results below.</p><div style={{background:C.indigo+"18",border:`1px solid ${C.indigo}33`,borderRadius:px(12),padding:"20px",marginBottom:px(24)}}><div style={{fontSize:px(13),color:C.muted,marginBottom:px(4)}}>Questions Answered</div><div style={{fontSize:px(40),fontWeight:900,color:C.white}}>{answered}/{totalQ}</div></div><div style={{display:"flex",gap:px(10)}}><button onClick={()=>{setPhase("start");setCur(0);setAnswers({});setFlagged(new Set());setTimeLeft(EXAM.duration*60);}} style={{flex:1,padding:"12px 0",borderRadius:px(10),background:"transparent",border:`1px solid ${C.border}`,color:C.muted,fontWeight:600,cursor:"pointer"}}>Retake</button><button style={{flex:2,padding:"12px 0",borderRadius:px(10),background:C.green,border:"none",color:"#fff",fontWeight:700,cursor:"pointer"}}>View Results </button></div></div></div>);
return(<div style={{minHeight:"100vh",background:C.navy,fontFamily:"'Inter',system-ui,sans-serif",display:"flex",flexDirection:"column"}}><div style={{position:"sticky",top:0,zIndex:50,background:C.navyMid,borderBottom:`1px solid ${C.border}`,padding:"0 24px",height:px(60),display:"flex",alignItems:"center",gap:px(16)}}><div style={{fontWeight:700,fontSize:px(14),color:C.white,flexShrink:0}}>{EXAM.subject}  {EXAM.year} {EXAM.type}</div><div style={{flex:1,height:px(4),background:C.border,borderRadius:px(2)}}><div style={{width:`${pct}%`,height:"100%",background:`linear-gradient(90deg,${C.indigo},${C.gold})`,borderRadius:px(2),transition:"width 0.3s"}}/></div><div style={{display:"flex",alignItems:"center",gap:px(8),padding:"6px 14px",borderRadius:px(100),background:timeLeft<300?C.error+"22":C.navyCard,border:`1px solid ${timeLeft<300?C.error:C.border}`,flexShrink:0}}><span style={{fontSize:px(14)}}></span><span style={{fontFamily:"monospace",fontWeight:800,fontSize:px(16),color:timeColor}}>{fmt(timeLeft)}</span></div><span style={{fontSize:px(13),color:C.muted,flexShrink:0}}>{answered}/{totalQ}</span><button onClick={()=>setPhase("confirm")} style={{padding:"8px 18px",borderRadius:px(8),background:C.green,border:"none",color:"#fff",fontWeight:700,fontSize:px(13),cursor:"pointer",flexShrink:0}}>Submit</button></div>
<div style={{display:"flex",flex:1,minHeight:0}}><div style={{width:px(200),background:C.navyMid,borderRight:`1px solid ${C.border}`,padding:px(16),overflowY:"auto",flexShrink:0}}><div style={{fontSize:px(11),color:C.muted,fontWeight:600,letterSpacing:"1px",textTransform:"uppercase",marginBottom:px(10)}}>Questions</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:px(6)}}>{QS.map((q,i)=>{const ans=answers[q.id]!==undefined;const flag=flagged.has(q.id);const isCur=cur===i;return(<div key={i} onClick={()=>setCur(i)} style={{aspectRatio:"1",display:"flex",alignItems:"center",justifyContent:"center",borderRadius:px(8),cursor:"pointer",fontSize:px(12),fontWeight:700,border:`1px solid ${isCur?C.indigo:flag?C.gold:ans?C.green:C.border}`,background:isCur?C.indigo:flag?C.gold+"22":ans?C.green+"22":C.navyCard,color:isCur?"#fff":flag?C.gold:ans?C.green:C.muted,position:"relative"}}>{i+1}{flag&&<span style={{position:"absolute",top:-2,right:-2,fontSize:px(8)}}></span>}</div>);})}
</div><div style={{marginTop:px(16),display:"flex",flexDirection:"column",gap:px(6),fontSize:px(11)}}>{[{color:C.green,label:"Answered"},{color:C.gold,label:"Flagged"},{color:C.border,label:"Unanswered"}].map(l=>(<div key={l.label} style={{display:"flex",alignItems:"center",gap:px(6)}}><div style={{width:px(10),height:px(10),borderRadius:px(2),background:l.color}}/><span style={{color:C.muted}}>{l.label}</span></div>))}</div></div>
<div style={{flex:1,padding:px(32),overflowY:"auto",maxWidth:px(800),margin:"0 auto",width:"100%"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:px(24)}}><div style={{display:"flex",gap:px(8),alignItems:"center"}}><span style={{background:C.indigo+"22",color:C.indigoL,padding:"4px 12px",borderRadius:px(100),fontSize:px(12),fontWeight:600}}>Q{cur+1}/{totalQ}</span><span style={{background:C.gold+"18",color:C.gold,padding:"4px 12px",borderRadius:px(100),fontSize:px(12),fontWeight:600}}>{q.marks} mark{q.marks>1?"s":""}</span><span style={{background:C.teal+"18",color:C.teal,padding:"4px 10px",borderRadius:px(100),fontSize:px(11)}}>{q.topic}</span></div><button onClick={()=>toggleFlag(q.id)} style={{padding:"6px 14px",borderRadius:px(8),background:flagged.has(q.id)?C.gold+"22":"transparent",border:`1px solid ${flagged.has(q.id)?C.gold:C.border}`,color:flagged.has(q.id)?C.gold:C.muted,fontSize:px(12),fontWeight:600,cursor:"pointer"}}>{flagged.has(q.id)?" Flagged":" Flag"}</button></div>
<div style={{...card({padding:"24px",marginBottom:px(24),background:C.navyMid})}}><p style={{fontSize:px(17),lineHeight:1.7,color:C.white,fontWeight:500,margin:0}}>{q.text}</p></div>
{q.type==="mcq"&&<MCQ q={q} ans={answers[q.id]} onAns={v=>setAns(q.id,v)}/>}
{q.type==="truefalse"&&<TF q={q} ans={answers[q.id]} onAns={v=>setAns(q.id,v)}/>}
{q.type==="short"&&<SA q={q} ans={answers[q.id]} onAns={v=>setAns(q.id,v)}/>}
<div style={{display:"flex",justifyContent:"space-between",marginTop:px(32)}}><button onClick={()=>setCur(c=>Math.max(0,c-1))} disabled={cur===0} style={{padding:"11px 22px",borderRadius:px(10),background:"transparent",border:`1px solid ${C.border}`,color:cur===0?C.border:C.white,fontWeight:600,fontSize:px(14),cursor:cur===0?"not-allowed":"pointer",opacity:cur===0?0.4:1}}> Previous</button><button onClick={()=>cur<totalQ-1?setCur(c=>c+1):setPhase("confirm")} style={{padding:"11px 28px",borderRadius:px(10),background:cur<totalQ-1?C.indigo:C.green,border:"none",color:"#fff",fontWeight:700,fontSize:px(14),cursor:"pointer"}}>{cur<totalQ-1?"Next ":"Submit Exam "}</button></div></div></div>
{phase==="confirm"&&(<div style={{position:"fixed",inset:0,zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(10,22,40,0.9)",backdropFilter:"blur(8px)",padding:px(24)}}><div style={{...card({padding:"32px 28px",maxWidth:px(420),width:"100%"}),textAlign:"center"}}><div style={{fontSize:px(48),marginBottom:px(12)}}></div><h2 style={{fontSize:px(22),fontWeight:800,color:C.white,marginBottom:px(8)}}>Submit Exam?</h2><p style={{color:C.muted,fontSize:px(14),marginBottom:px(20)}}>You answered <strong style={{color:C.white}}>{answered}</strong> of <strong style={{color:C.white}}>{totalQ}</strong> questions.{totalQ-answered>0&&` ${totalQ-answered} unanswered.`}</p>{totalQ-answered>0&&<div style={{background:C.gold+"12",border:`1px solid ${C.gold}33`,borderRadius:px(10),padding:"10px 14px",marginBottom:px(20),fontSize:px(13),color:C.gold}}> Unanswered questions score zero.</div>}<div style={{display:"flex",gap:px(10)}}><button onClick={()=>setPhase("exam")} style={{flex:1,padding:"12px 0",borderRadius:px(10),background:"transparent",border:`1px solid ${C.border}`,color:C.muted,fontWeight:600,fontSize:px(14),cursor:"pointer"}}>Go Back</button><button onClick={()=>{clearInterval(timerRef.current);setPhase("done");}} style={{flex:2,padding:"12px 0",borderRadius:px(10),background:C.green,border:"none",color:"#fff",fontWeight:700,fontSize:px(14),cursor:"pointer"}}>Submit Now </button></div></div></div>)}
</div>);}
=======
export default function Phase4() {
  const C = {
    navy:"#0A1628", navyMid:"#0F1F3D", navyCard:"#111E35",
    indigo:"#4F46E5", indigoL:"#6366F1", gold:"#F59E0B",
    white:"#F0F4FF", muted:"#94A3B8", border:"rgba(99,102,241,0.18)",
  };
  return (
    <div style={{display:"flex",minHeight:"100vh",background:C.navy,color:C.white,fontFamily:"'Inter',system-ui,sans-serif"}}>
      <div style={{width:220,minHeight:"100vh",background:C.navyMid,borderRight:"1px solid "+C.border,display:"flex",flexDirection:"column",padding:"24px 0",flexShrink:0}}>
        <div style={{padding:"0 20px 24px",borderBottom:"1px solid "+C.border,display:"flex",alignItems:"center",gap:10}}>
          <div style={{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,"+C.indigo+","+C.gold+")",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:16,color:"#fff"}}>E</div>
          <div>
            <div style={{fontWeight:800,fontSize:15,color:C.white}}>ExamHub</div>
            <div style={{fontSize:11,color:C.gold,fontWeight:600}}>Tanzania</div>
          </div>
        </div>
        <nav style={{padding:"12px 10px",flex:1}}>
          {[["Home","/"],["Dashboard","/dashboard"],["Past Papers","/papers"],["Analytics","/analytics"],["Activities","/activities"],["Admin","/admin"]].map(([label,path])=>(
            <a key={label} href={path} style={{display:"flex",alignItems:"center",padding:"10px 12px",borderRadius:10,marginBottom:2,color:C.muted,textDecoration:"none",fontSize:13,border:"1px solid transparent"}}>{label}</a>
          ))}
        </nav>
      </div>
      <div style={{flex:1,display:"flex",flexDirection:"column"}}>
        <div style={{padding:"16px 24px",borderBottom:"1px solid "+C.border,background:C.navy,position:"sticky",top:0,zIndex:10}}>
          <div style={{fontSize:20,fontWeight:800,color:C.white}}>Digital Exam Engine</div>
          <div style={{fontSize:13,color:C.muted,marginTop:2}}>Phase 4 — Run ExamHub-Complete-Setup.ps1 to load full component</div>
        </div>
        <main style={{flex:1,padding:"40px 24px",display:"flex",alignItems:"center",justifyContent:"center"}}>
          <div style={{textAlign:"center",maxWidth:480}}>
            <div style={{fontSize:64,marginBottom:16}}>📋</div>
            <h2 style={{fontSize:22,fontWeight:800,color:C.white,marginBottom:10}}>Digital Exam Engine</h2>
            <p style={{color:C.muted,fontSize:14,lineHeight:1.7,marginBottom:28}}>
              The full Phase 4 component is in <strong style={{color:C.indigoL}}>ExamHub-Complete-Setup.ps1</strong>. Run it on your Windows machine and the full UI will appear here.
            </p>
            <div style={{display:"flex",gap:12,justifyContent:"center"}}>
              <a href="/" style={{padding:"11px 22px",borderRadius:10,background:C.indigo,color:"#fff",fontWeight:600,fontSize:14,textDecoration:"none"}}>Home</a>
              <a href="/dashboard" style={{padding:"11px 22px",borderRadius:10,background:"transparent",border:"1px solid "+C.border,color:C.muted,fontWeight:600,fontSize:14,textDecoration:"none"}}>Dashboard</a>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
>>>>>>> 0b3c81e9470c74fd27c37a680978282ae4c33e18
