// ── Excel / CSV Export Utility ─────────────────────────────────────────────
// Pure CSV export (works in all browsers, opens in Excel perfectly)
// For full .xlsx: install SheetJS — npm install xlsx

export interface ExcelColumn { header: string; key: string; width?: number; format?: "number" | "percent" | "date" | "text"; }
export interface ExcelOptions {
  filename: string;
  sheetName?: string;
  columns: ExcelColumn[];
  rows: Record<string, unknown>[];
  title?: string;
}

/** Format a cell value based on column format */
function formatCell(value: unknown, format?: string): string {
  if (value === null || value === undefined) return "";
  if (format === "percent") return `${value}%`;
  if (format === "date") return new Date(value as string).toLocaleDateString("en-TZ");
  return String(value);
}

/** Export to CSV — opens natively in Excel/LibreOffice */
export function exportToCSV(options: ExcelOptions) {
  const { filename, columns, rows, title } = options;
  const lines: string[] = [];

  // Title row
  if (title) {
    lines.push(`"${title}"`);
    lines.push(`"Exported: ${new Date().toLocaleString("en-TZ")}"`);
    lines.push("");
  }

  // Header row
  lines.push(columns.map(c => `"${c.header}"`).join(","));

  // Data rows
  rows.forEach(row => {
    const cells = columns.map(c => {
      const val = formatCell(row[c.key], c.format);
      return `"${val.replace(/"/g, '""')}"`;
    });
    lines.push(cells.join(","));
  });

  // Summary row
  lines.push("");
  lines.push(`"Total Records","${rows.length}"`);
  lines.push(`"Generated by","ExamHub Tanzania"`);

  const csv = "\uFEFF" + lines.join("\r\n"); // BOM for Excel UTF-8
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Export multiple sheets as separate CSV downloads */
export function exportMultiSheet(sheets: ExcelOptions[]) {
  sheets.forEach((sheet, i) => {
    setTimeout(() => exportToCSV(sheet), i * 300);
  });
}

/** Generate summary stats for a numeric column */
export function columnStats(rows: Record<string, unknown>[], key: string): { min: number; max: number; avg: number; sum: number } {
  const nums = rows.map(r => Number(r[key])).filter(n => !isNaN(n));
  if (!nums.length) return { min: 0, max: 0, avg: 0, sum: 0 };
  return {
    min: Math.min(...nums),
    max: Math.max(...nums),
    avg: Math.round(nums.reduce((a, b) => a + b, 0) / nums.length),
    sum: nums.reduce((a, b) => a + b, 0),
  };
}
